version: 2.0

jobs:
  build-deploy-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Clear cache
          command: |
            npm cache clean --force
      - run:
          name: Build and push Docker image to Heroku Staging App
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME_STAGING} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME_STAGING} web
  build-deploy-production:
    machine: true
    steps:
      - checkout
      - run:
          name: Clear cache
          command: |
            npm cache clean --force
      - run:
          name: Build and push Docker image to Heroku Production App
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME_PRODUCTION} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME_PRODUCTION} web

workflows:
  version: 2
  build-deploy-staging:
    jobs:
      - build-deploy-staging:
          filters:
            branches:
              only: 
                - staging
              ignore: 
                - main
  build-deploy-production:
    jobs:
      - build-deploy-production:
          filters:
            branches:
              only: 
                - main
              ignore: 
                - staging
